import type { Booking } from "./types"

export const mockBookings: Booking[] = [
  {
    id: "bk_001",
    reference: "JK-4821",
    customerId: "cust_01",
    customerName: "Thandi Mokoena",
    customerPhone: "+27 82 555 0101",
    driverId: "drv_john",
    driverName: "John Khumalo",
    serviceId: "drive-me-home",
    pickup: {
      address: "The Lookout Deck, Lookout Beach, Plettenberg Bay",
      lat: -34.0625,
      lng: 23.3717,
    },
    dropoff: {
      address: "14 Cormorant Drive, Plettenberg Bay",
      lat: -34.048,
      lng: 23.39,
    },
    stops: [],
    dateTime: new Date(Date.now() + 1000 * 60 * 60 * 22).toISOString(),
    returnTrip: false,
    passengerCount: 2,
    usesCustomerVehicle: true,
    requiresFemaleDriver: false,
    childPickup: false,
    distanceKm: 6.4,
    durationMinutes: 14,
    estimatedPrice: 310,
    status: "confirmed",
    paymentStatus: "paid",
    notes: "Black BMW, parked on the left as you arrive.",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
  },
  {
    id: "bk_002",
    reference: "JK-4822",
    customerId: "cust_02",
    customerName: "Pieter van der Merwe",
    customerPhone: "+27 83 555 0202",
    driverId: "drv_john",
    driverName: "John Khumalo",
    serviceId: "wine-farm",
    pickup: {
      address: "Hog Hollow Country Lodge, The Crags",
      lat: -33.978,
      lng: 23.524,
    },
    dropoff: {
      address: "Hog Hollow Country Lodge, The Crags",
      lat: -33.978,
      lng: 23.524,
    },
    stops: [
      { address: "Bramon Wine Estate, The Crags" },
      { address: "Newstead Lund Family Vineyards, Plettenberg Bay" },
    ],
    dateTime: new Date(Date.now() + 1000 * 60 * 60 * 48).toISOString(),
    returnTrip: true,
    passengerCount: 4,
    usesCustomerVehicle: true,
    requiresFemaleDriver: false,
    childPickup: false,
    distanceKm: 42,
    durationMinutes: 240,
    estimatedPrice: 950,
    status: "driver_assigned",
    paymentStatus: "pending",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
  },
  {
    id: "bk_003",
    reference: "JK-4823",
    customerId: "cust_03",
    customerName: "Lerato Dlamini",
    customerPhone: "+27 84 555 0303",
    driverId: "drv_junior",
    driverName: "Junior Khumalo",
    serviceId: "child-pickup",
    pickup: {
      address: "Plettenberg Primary School, Plettenberg Bay",
      lat: -34.053,
      lng: 23.375,
    },
    dropoff: {
      address: "28 Beachy Head Drive, Plettenberg Bay",
      lat: -34.067,
      lng: 23.378,
    },
    stops: [],
    dateTime: new Date(Date.now() + 1000 * 60 * 60 * 20).toISOString(),
    returnTrip: false,
    passengerCount: 1,
    usesCustomerVehicle: false,
    requiresFemaleDriver: true,
    childPickup: true,
    childDetails: {
      childName: "Nia Dlamini (7)",
      school: "Plettenberg Primary",
      authorisedAdult: "Lerato Dlamini (mother)",
      emergencyContact: "+27 84 555 0303",
      instructions: "Collect from Grade 2 gate at 13:30.",
    },
    distanceKm: 4.2,
    durationMinutes: 12,
    estimatedPrice: 240,
    status: "confirmed",
    paymentStatus: "paid",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
  },
  {
    id: "bk_004",
    reference: "JK-4820",
    customerId: "cust_01",
    customerName: "Thandi Mokoena",
    serviceId: "airport",
    pickup: {
      address: "14 Cormorant Drive, Plettenberg Bay",
    },
    dropoff: {
      address: "George Airport (GRJ)",
    },
    stops: [],
    dateTime: new Date(Date.now() - 1000 * 60 * 60 * 24 * 7).toISOString(),
    returnTrip: false,
    passengerCount: 2,
    usesCustomerVehicle: false,
    requiresFemaleDriver: false,
    childPickup: false,
    distanceKm: 185,
    durationMinutes: 135,
    estimatedPrice: 650,
    finalPrice: 650,
    status: "completed",
    paymentStatus: "paid",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 10).toISOString(),
  },
  {
    id: "bk_005",
    reference: "JK-4819",
    customerId: "cust_04",
    customerName: "Sipho Nkosi",
    serviceId: "event-pickup",
    pickup: {
      address: "Enrico Restaurant, Keurboomstrand",
    },
    dropoff: {
      address: "Robberg Beach Lodge, Plettenberg Bay",
    },
    stops: [],
    dateTime: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
    returnTrip: false,
    passengerCount: 3,
    usesCustomerVehicle: true,
    requiresFemaleDriver: false,
    childPickup: false,
    distanceKm: 9.8,
    durationMinutes: 18,
    estimatedPrice: 290,
    finalPrice: 290,
    status: "completed",
    paymentStatus: "paid",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString(),
  },
]

export const mockDrivers = [
  {
    id: "drv_john",
    name: "John Khumalo",
    phone: "+27 82 123 4567",
    rating: 4.9,
    trips: 1284,
    verified: true,
    female: false,
    languages: ["English", "isiZulu", "Afrikaans"],
  },
  {
    id: "drv_junior",
    name: "Junior Khumalo",
    phone: "+27 82 987 6543",
    rating: 5.0,
    trips: 412,
    verified: true,
    female: true,
    languages: ["English", "isiZulu"],
  },
]
